jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      curl -LJO https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip
    displayName: 'Get Ninja build'
    continueOnError: false
    
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'ninja-win.zip' 
      destinationFolder: ED64-XIO/tools
      cleanDestinationFolder: false 
    displayName: 'Extract ninja build'
    #condition: ne(variables.GCC_CACHE_RESTORED, 'true')
    continueOnError: false  

  - script: |
      curl -L https://n64tools.blob.core.windows.net/binaries/N64-tools/mips64-gcc-toolchain/master/latest/gcc-toolchain-mips64-win64.zip --output gcc-toolchain-mips64-win64.zip
    displayName: 'Get GCC toolchain'
    continueOnError: false

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'gcc-toolchain-mips64-win64.zip' 
      destinationFolder: ED64-XIO/toolchain/gcc-toolchain-mips64
      cleanDestinationFolder: false 
    displayName: 'Extract gcc-toolchain-mips64-win64'
    #condition: ne(variables.GCC_CACHE_RESTORED, 'true')
    continueOnError: false

  - script: |
      curl -L https://n64tools.blob.core.windows.net/binaries/N64-tools/libdragon/develop/latest/libdragon-win64.zip --output libdragon-win64.zip
    displayName: 'Get libdragon'
    continueOnError: false

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'libdragon-win64.zip' 
      destinationFolder: ED64-XIO/toolchain/libdragon
      cleanDestinationFolder: false 
    displayName: 'Extract libdragon-win64'
    continueOnError: false

  - script: echo "##vso[task.prependpath]$(Build.SourcesDirectory)\ED64-XIO\tools"
    displayName: Tweak PATH for Ninja

    #not sure why this is needed, but fails if not there!
  - script: echo "##vso[task.prependpath]$(Build.SourcesDirectory)\ED64-XIO\toolchain\libdragon\tools"
    displayName: Tweak PATH for libdragon tools

    #not sure why this is needed, but fails if not there!
  - script: echo "##vso[task.prependpath]C:\Windows\System32"
    displayName: Tweak PATH for cmd

  - task: CMake@1
    inputs:
      cmakeArgs:
        -G Ninja 
        -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/ED64-XIO/CMake/toolchain-libdragon.cmake
        -DTOOLCHAIN_PREFIX=$(Build.SourcesDirectory)/ED64-XIO/toolchain/gcc-toolchain-mips64
        -DLIBDRAGON_PREFIX=$(Build.SourcesDirectory)/ED64-XIO/toolchain/libdragon
        $(Build.SourcesDirectory)/ED64-XIO/
    displayName: Set CMake Options

    #Builds to the rootdir/build?
  - task: CMake@1
    inputs:
      cmakeArgs: '--build $(Build.SourcesDirectory)/build --target all --config Release'
    displayName: Build with CMake

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/
      contents: 'build\*.v64' 
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
    displayName: 'Copy ROM'
    continueOnError: false

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'binaries' 
      publishLocation: 'Container'
    displayName: Publish Build Artifacts
    continueOnError: false