name: Build Usb64 App
 
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '3.0', '3.1.x' ]
    name: Build ${{ matrix.dotnet }} usb64
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
