name: Build Linux Usb64 App
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ 'net6.0' ]
    name: Build ${{ matrix.dotnet }} usb64 Linux
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
     
      - name: Setup .NET Core 6.0
        if: matrix.dotnet == 'net6.0'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@latest
      
      - name: Restore NuGet Packages
        run: nuget restore ./usb64/usb64.sln
  
      - name: Build App
        run: dotnet build ./usb64/usb64.sln --configuration Release --no-restore --framework ${{ matrix.dotnet }}
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: usb64-${{ matrix.dotnet }}-app-linux
          path: |
            ${{ github.workspace }}/usb64/usb64/bin/Release/${{ matrix.dotnet }}/usb64.dll