name: Build ED64 XIO N64 test ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      #docker for libdragon?
      - run: sudo npm install -g libdragon
      - run: libdragon download
      - run: sudo chmod 777 -R ${{ github.workspace }}/ED64-XIO/
      - run: cd ${{ github.workspace }}/ED64-XIO/ && sudo libdragon start
      # # -- -C ${{ github.workspace }}/ED64-XIO/
      - run: cd ${{ github.workspace }}/ED64-XIO/ && sudo libdragon make