name: Build ED64 Example ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        releasetype: [ 'debug', 'release' ]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Install Toolchain Docker Container
        run: |
          docker pull ghcr.io/dragonminded/libdragon:latest

      - name: Setup Libdragon
        run: |
          docker run \
          --mount type=bind,source=$(pwd),target=/libdragon \
          --workdir=/libdragon \
          ghcr.io/dragonminded/libdragon:latest \
          make libdragon NDEBUG


      - name: Setup Build environment
        run: |
          cd ${{ github.workspace }}/ED64-XIO/
          mkdir bin && mkdir bin/release && mkdir bin/debug && mkdir obj

      - name: Build ROM
        run: cd ${{ github.workspace }}/ED64-XIO/ && libdragon make ${{ matrix.releasetype }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ED64-XIO-SAMPLE_N64_ROM-${{ matrix.releasetype }}
          path: ${{ github.workspace }}/ED64-XIO/bin/${{ matrix.releasetype }}/ED64-XIO-SAMPLE.v64
