name: Build ED64 Example ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        releasetype: [ 'debug', 'release' ]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Install Libdragon container
        run: |
          sudo npm install -g libdragon
          libdragon init
          #libdragon exec bash -c 'export N64_CFLAGS="-DNDEBUG"'
          #libdragon exec bash -c N64_CFLAGS="-DNDEBUG"
          #N64_CFLAGS="-DNDEBUG" && libdragon install
          sed -z -i.bak 's/CFLAGS+=$(N64_CFLAGS) /CFLAGS+=$(N64_CFLAGS) -DNDEBUG /' ./libdragon/Makefile
          
          #cd ./libdragon/
          cat > debug_h.patch << EOF
          diff --git a/include/debug.h b/include/debug.h
          index 1bc8404..9ceec9c 100644
          --- a/include/debug.h
          +++ b/include/debug.h
          @@ -199,7 +199,7 @@ extern "C" {
                  #define debug_init_sdlog(fn,fmt)   ({ false; })
                  #define debug_init_sdfs(prefix,np) ({ false; })
                  #define debugf(msg, ...)           ({ })
          -       #define assertf(expr, msg, ...)    ({ })
          +       #define assertf(expr, msg, ...)    ({ (void)(expr); })
          #endif

          /** @brief Underlying implementation function for assert() and #assertf. */
          diff --git a/src/audio/libxm/context.c b/src/audio/libxm/context.c
          index 590e14c..6af483a 100644
          --- a/src/audio/libxm/context.c
          +++ b/src/audio/libxm/context.c
          @@ -396,7 +396,7 @@ static uint32_t varint_get(uint8_t **pp) {
          int xm_context_decompress_pattern(uint8_t *in, int sz, xm_pattern_slot_t *pat) {
                  uint8_t *in_end = in+sz;
                  uint8_t *out = (uint8_t*)pat;
          -       bool direction = (out<=in);
          +       bool direction = (out<=in); (void)direction;
                  while (in < in_end) {
                          int zeros = varint_get(&in);
                          int runs = zeros & 7; if (runs == 7) runs += varint_get(&in);
          diff --git a/src/audio/libxm/play.c b/src/audio/libxm/play.c
          index 32d50fe..0a1c22c 100644
          --- a/src/audio/libxm/play.c
          +++ b/src/audio/libxm/play.c
          @@ -894,7 +894,7 @@ static void xm_row(xm_context_t* ctx) {
                                  fread(cmp_data, cmp_size, 1, ctx->fh);

                                  int sz = xm_context_decompress_pattern(cmp_data, cmp_size, ctx->slot_buffer);
          -                       assert(sz == dec_size);
          +                       assert(sz == dec_size); (void)sz;
                          }
                          ctx->slot_buffer_index = pat_idx;
                  }
          diff --git a/src/debug.c b/src/debug.c
          index 5e7d1ab..a9d5700 100644
          --- a/src/debug.c
          +++ b/src/debug.c
          @@ -2,7 +2,7 @@
            * @file debug.c
            * @brief Debugging Support
            */
          -
          +#undef NDEBUG
          #include <libdragon.h>
          #include <string.h>
          #include <fcntl.h>
          EOF

          patch < debug_h.patch
          #cd ..

          libdragon install

      - name: Setup Build environment
        run: |
          cd ${{ github.workspace }}/ED64-XIO/
          mkdir bin && mkdir bin/release && mkdir bin/debug && mkdir obj
          libdragon start

      - name: Build ROM
        run: cd ${{ github.workspace }}/ED64-XIO/ && libdragon make ${{ matrix.releasetype }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ED64-XIO-SAMPLE_N64_ROM-${{ matrix.releasetype }}
          path: ${{ github.workspace }}/ED64-XIO/bin/${{ matrix.releasetype }}/ED64-XIO-SAMPLE.v64
