name: Build ED64 XIO N64 test ROM
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      #todo: docker for libdragon?