name: CrossCompile CI Build for ED64CommsUtility 
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ 'net6.0' ] # ,'netcoreapp3.1'
        arch: [win-x64, linux-x64] # , osx-x64, win-x86, win-arm, win-arm64, linux-arm, linux-arm64 - see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog for further options. 
        configuration: [ 'Release' ] # , 'Debug'
        contained: [self-contained] # , no-self-contained

    name: Building ${{ matrix.dotnet }}-${{ matrix.configuration }} App for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
        with:
          fetch-depth: 1

      - name: Setup .NET 6.0
        if: matrix.dotnet == 'net6.0'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
               
      - name: Build App
        run: |
          # note: we don''t use 'dotnet build' as it does not support '--runtime', but 'dotnet publish' does and still includes the build process.
          # dotnet restore ./ED64CommsUtility/ED64CommsUtility/ED64CommsUtility.csproj
          dotnet publish ./ED64CommsUtility/ED64CommsUtility.sln --configuration ${{ matrix.configuration }} --runtime ${{ matrix.arch }} --${{ matrix.contained }} --framework ${{ matrix.dotnet }}
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ED64CommsUtility-${{ matrix.dotnet }}-${{ matrix.configuration }}-${{ matrix.arch }}-${{ matrix.contained }}
          path: |
            # Wildcard the publish directory rather than trying to target DLL and EXE files.
            # Could probably improve by "merging" files into EXE. and exclude json files. See: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli ( -p:PublishSingleFile=true) etc.
            ${{ github.workspace }}/ED64CommsUtility/ED64CommsUtility/bin/${{ matrix.configuration }}/${{ matrix.dotnet }}/${{ matrix.arch }}/publish/**/*
