name: Build Linux Usb64 App
 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x', '6.0.x' ]
    name: Build ${{ matrix.dotnet }} usb64 Linux
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: Build App
        run: dotnet build ./usb64/usb64.sln --configuration Release --no-restore --framework ${{ matrix.dotnet }}
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: usb64-${{ matrix.dotnet }}-app-linux
          path: |
            ${{ github.workspace }}/usb64/usb64/bin/Release/${{ matrix.dotnet }}/usb64.dll